### ISSUE TITLE
rubgems version is outdated.

### ISSUE THREAD

**Issue by sime** [blockcypher/ruby-client#20]
Hello,

The rubygems version of blockcypher-ruby is a little out of date: https://rubygems.org/gems/blockcypher-ruby

The current version is 0.2.3, though rubygems lists it at 0.2.2.

:)

**Comment by acityinohio** [comment]
Just bumped it to 0.2.4 in preparation for our confidence change, sorry it took so long to bring it up to date! https://rubygems.org/gems/blockcypher-ruby
