### ISSUE TITLE
Path forward for other currency support

### ISSUE THREAD

**Issue by ramontayag** [blockcypher/ruby-client#26]
Not sure if this gem is still being maintained, but are there plans to support other currencies?

I'm looking at using Blockcypher's Ethereum API, and it made sense to add the capability to this gem. Looking at the code, it looks like there was work at the beginning to support other currencies, but this effort seems to have stopped -- there are a bunch of hard-coded references to `Bitcoin::Key`. Do the other currencies work?

**Comment by catsky** [comment]
same question as above

**Comment by suiody** [comment]
نعم انها تعمل

**Comment by Suneel-RoR** [comment]
Does anyone created sample application using this gem.

**Comment by quentinlesceller** [comment]
I think this is definitely a feature that we'd like to support on the ruby-client.

**Comment by quentinlesceller** [comment]
You can use Ethereum with this library now.
